export const isDesktop = window.innerHeight <= 800;
export const primaryColor = "#2c7be5";
export const secondaryColor = "#ECB054";
export const LocalStorageKey = "carsafai_admin_";
// export const adminApiBaseUrl = process.env.REACT_APP_ADMIN_API_URL;
export const adminApiBaseUrl = "http://carsafai.deliverable.services/admin/v1/";
export const appApiBaseUrl = process.env.REACT_APP_APP_API_URL;
// export const baseUploadUrl = process.env.REACT_APP_UPLOAD_URL;
export const baseUploadUrl = "http://carsafai.deliverable.services/upload/";
export const clientWebUrl = process.env.REACT_APP_CLIENT_WEB_URL;
